baseURL: "https://www.adrienbouttier.com"
languageCode: "fr-FR"
title: "Adrien BOUTTIER"
theme: hugo-theme

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  title: "Adrien BOUTTIER"
  # description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/logo.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "Adrien BOUTTIER" # Brand name for the brand | default is the title variable
    disableSearch: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableTechnologies: false
      disableContact: true

  hero:
    enable: true
    intro: "Hello, my name is"
    title: "Adrien BOUTTIER"
    aka: ">> adrnbttr"
    avatar: "/me.jpeg"
    subtitle: "Senior Software Engineer"
    content: "**Data** is the focus"
    image: /me.jpeg
    button:
      enable: false
      name: "CV"
      url: "#"
      download: true
      newPage: false
    github:
      enable: true
      name: ""
      url: "https://github.com/adrnbttr"
      icon: fab fa-github
    linkedin:
      enable: true
      name: ""
      url: "https://www.linkedin.com/in/adrien-bouttier/"
      icon: fab fa-linkedin

  about:
    enable: true
    title: "About me"
    image: "/me.jpeg"
    content: |-
      With over 15 years of experience as a Fullstack developer, my true passion has always centered on backend optimization, data management, and databases. As soon as the opportunity arose, I undertook a 3-month certified training to deepen my skills in data engineering. Since then, I've been consistently training, primarily through Udemy and Datacamp, showcasing my ongoing dedication to the world of Data.

      Recently, I have further augmented my professional qualifications by achieving a B2 certification in the IELTS English language assessment, underscoring my ability to engage in an international work environment effectively.

      Currently involved in a project for my end-of-studies dissertation as part of an evening engineering course, I am actively seeking opportunities with a strong focus on Data. 

  experience-old:
    enable: true
    title: "Expériences"
    items:
      - job: "Senior Software Developer"
        company: "Facebook"
        companyUrl: "https://example.com"
        date: "Jan 2022 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

      - job: "Software Developer"
        company: "Amazon"
        companyUrl: "https://example.com"
        date: "Sep 2020 - Dec 2021"
        featuredLink:
          enable: true
          url: "https://example.com"
        info:
          enable: true
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

      - job: "Junior Software Developer"
        company: "Apple"
        companyUrl: "https://example.com"
        date: "Jan 2020 - Aug 2020"
        info:
          enable: false
        featuredLink:
          enable: true
          url: "https://example.com"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

      - job: "UI/UX Designer"
        company: "Netflix"
        companyUrl: "https://example.com"
        date: "June 2017 - Nov 2019"
        featuredLink:
          enable: true
          url: "https://example.com"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

      - job: "Product Designer"
        company: "Google"
        companyUrl: "https://example.com"
        date: "Feb 2016 - Mar 2017"
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  experience:
    enable: true
    title: "Experiences"
    index: false
    items:
      - title: "Senior Data & Software Engineer"
        company:
          name: "Marvin Recruiter"
        date: "Sept 2023 - Feb, 2024"
        localisation: "Remote"
        content: |-
            - Optimize database design
            - Improve data pipeline, suggestion, and matching algorithms
            - Revamp REST API and vue.js frontend
            - Implement event-driven architecture
        items:
          - Python
          - Node.JS
          - Vue3.JS
          - Database design
          - SQL / NoSQL Query
          - NLP (Natural Language Processing)
          - Machine Learning
          - Scala
          - Event-driven architectures
          - MongoDB
          - Algolia
          - Terraform
          - CI / CD
          - Docker
          - Google Cloud Platform (Pub/Sub - Serverless - Scheduler - Atlas)

      - title: "Lead Backend Engineer"
        company:
          name: "Popwork"
        date: "Aug. 2022 - Nov. 2022"
        localisation: "Remote"
        content: |-
            - Enhancement of a GraphQL API
            - Improve the data pipeline
            - Optimization of MongoDB queries
            - CI/CD process improvement with GitHub Actions and Google Cloud Platform
        items:
          - TypeScript
          - Node.JS
          - MongoDB
          - API Rest & GraphQL
          - SQL Query
          - Database design
          - CI / CD
          - Docker
          - Google Cloud Platform
          - Event-driven architectures

      - title: "Senior Full-Stack / Backend Engineer"
        company:
          name: "JobyPepper"
        date: "Oct. 2018 - Aug. 2022"
        localisation: "Remote"
        content: |-
            - REST API enhancement with automated testing
            - Data processing optimization using MongoDB
            - Microservices architecture refinement
            - CI/CD implementation with Kubernetes and Google Cloud Platform
            - Development and enhancement of ReactJS frontend
            - Contribution to the ReactNative mobile application
        items:
          - Node.JS
          - MongoDB
          - API Rest
          - SQL Query
          - Database design
          - CI / CD
          - Docker
          - Kubernetes
          - Ansible
          - Microservices
          - Event-driven architectures
          - RabbitMQ
          - Google Cloud Platform
          - Unit & functional testing
          - React.JS
          - Oauth2

      - title: "Senior Backend Engineer"
        company:
          name: "JobyPepper"
        date: "Oct. 2017 - Sept. 2018"
        localisation: "Remote - Freelance"
        content: |-
            - Securing a REST API with OAuth2
            - Establishing microservices architecture
        items:
          - Node.JS
          - MongoDB
          - API Rest
          - SQL Query
          - Database design
          - Docker
          - Microservices
          - Event-driven architectures
          - RabbitMQ
          - Google Cloud Platform
          - Unit & functional testing
          - Oauth2

      - title: "Lead Full-Stack Engineer"
        company:
          name: "Wanadev"
        date: "Jun. 2014 - Sept. 2018"
        localisation: "Lyon"
        content: |-
            - Migration of a PHP API to NodeJS
            - Database migration from MySQL to PostgreSQL
            - Securing the API with an OAuth2 layer
            - Creation and optimization of SQL queries
            - Creating an interface for making ElasticSearch queries
            - Development of NodeJS microservices
            - Client relations
        items:
          - Node.JS
          - PostgreSQL
          - API Rest
          - SQL Query
          - Database design
          - CI / CD
          - Docker
          - Framework Symfony
          - Unit & functional testing
          - React.JS
          - Elastics Search
          - Event-driven architectures

      - title: "Web Developer"
        company:
          name: "KNP Labs"
        date: "Jan. 2014 - May 2014"
        localisation: "Remote"
        items:
          - Symfony framework
          - Database design
          - SQL Query
          - MySQL
          - Unit & functional testing

      - title: "Web Developer"
        company:
          name: "DotSoft"
        date: "Mar. 2009 - Jan. 2014"
        localisation: "Lyon"
        content: |-
            - Creation and optimization of SQL queries on a SQL Server database
            - Maintenance and development of e-commerce sites for retail
            - Maintenance and development of commercial management software
            - Client relations
        items:
          - Visual Basic .NET (VB.NET)
          - C#
          - ASP.NET
          - Database design
          - E-commerce
          - Microsoft SQL Server
          - SQL Query

      - title: ".Net Developer"
        company:
          name: "CGI"
        date: "Jul. 2008 - Mar. 2009"
        localisation: "Paris"
        items:
          - C#
          - Microsoft SQL Server
          - Database design
          - SQL Query

  education:
    enable: true
    title: "Education"
    index: false
    items:
      - title: "Software Engineer"
        school:
          name: "EICNAM"
        date: "2014 - 2024"

      - title: "Data Engineer"
        school:
          name: "DataScientest - Mines Paris PSL"
        date: "Jan. 2023 - Apr. 2023"
        content: "RNCP level 7 (Bac+5)"

      - title: "IELTS B2 Certification"
        school:
          name: "British Council"
        date: "2023"

      - title: "Bachelor's Degree in Computer Science (Equivalent to French Licence)"
        school:
          name: "CNAM"
        date: "2011 - 2014"

      - title: "IT Advanced Technician Certificate (Equivalent to French BTS)"
        school:
          name: "Lycée Douanier Rousseau - Laval"
        date: "2006 - 2008"

      - title: "Bank Advanced Technician Certificate (Equivalent to French BTS)"
        school:
          name: "CFPB - Lyon"
        date: "2004 - 2005"

  technologies:
    enable: true
    items:
      - title: Languages
        items:
          - title: Python
          - title: Scala
          - title: Rust
          - title: JavaScript
          - title: TypeScript
          - title: .Net C#

      - title: Framework
        items:
          - title: Node.JS
          - title: Nest.JS
          - title: Flask / FastAPI
          - title: Vue.JS
          - title: React.JS
          - title: "..."

      - title: Data Engineering
        items:
          - title: Python
          - title: Rust
          - title: Scala
          - title: Spark
          - title: Airflow
          - title: RabbitMQ
          - title: SQL Query
          - title: Database design
          - title: DataBrick
          - title: SnowFlake
          - title: Kafka
          - title: Power BI
          - title: Qlik Sense

      - title: Databases
        items:
          - title: PostgreSQL
          - title: MongoDB
          - title: SQL Server
          - title: MySQL
          - title: SQlite
          - title: ElasticSearch
          - title: Algolia
          - title: Neo4J

      - title: Local environnment
        items:
          - title: NeoVim / NvChad / Tmux 
          - title: Linux
          - title: Bépo Keyboard
          - title: MacOS
          - title: Visual Studio Code
          - title: Windows

      - title: DevOps
        items:
          - title: Google Cloud Platform
          - title: Scalingo
          - title: Docker
          - title: Ansible
          - title: Kubernetes
          - title: Terraform
          - title: Debian

      - title: CI / CD
        items:
          - title: GitHub Actions
          - title: Circle CI
          - title: GitLab CI

      - title: API
        items:
          - title: REST
          - title: GraphQL          

  projects:
    enable: false
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  contact:
    title: Contact
    enable: false
    email: adrnbttr@gmail.com
    btnName: Contactez-moi

  footer:
    socialNetworks:
      github: https://github.com/adrnbttr
      linkedin: https://www.linkedin.com/in/adrien-bouttier
      # twitter: https://twitter.com

  listPages:
    disableFeaturedImage: false
